"""Add lesson_id/type to Question, drop ComprehensionQuestion

Revision ID: 6838bf44552d
Revises: 6638e99596eb
Create Date: 2025-04-19 11:40:22.006856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6838bf44552d'
down_revision: Union[str, None] = '6638e99596eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comprehension_questions_id', table_name='comprehension_questions')
    op.drop_table('comprehension_questions')
    #op.drop_table('alembic_version')
    op.drop_index('ix_lessons_id', table_name='lessons')
    op.drop_index('ix_lessons_level', table_name='lessons')
    op.drop_index('ix_lessons_title', table_name='lessons')
    op.drop_index('ix_lessons_topic', table_name='lessons')
    op.create_index(op.f('ix_public_lessons_id'), 'lessons', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_lessons_level'), 'lessons', ['level'], unique=False, schema='public')
    op.create_index(op.f('ix_public_lessons_title'), 'lessons', ['title'], unique=False, schema='public')
    op.create_index(op.f('ix_public_lessons_topic'), 'lessons', ['topic'], unique=False, schema='public')
    op.add_column('questions', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('question_type', sa.String(), nullable=True))
    op.drop_index('ix_questions_id', table_name='questions')
    op.create_index(op.f('ix_public_questions_id'), 'questions', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_questions_lesson_id'), 'questions', ['lesson_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_questions_question_type'), 'questions', ['question_type'], unique=False, schema='public')
    op.create_foreign_key(None, 'questions', 'lessons', ['lesson_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index('ix_user_answers_id', table_name='user_answers')
    op.create_index(op.f('ix_public_user_answers_id'), 'user_answers', ['id'], unique=False, schema='public')
    op.drop_constraint('user_answers_user_id_fkey', 'user_answers', type_='foreignkey')
    op.drop_constraint('user_answers_question_id_fkey', 'user_answers', type_='foreignkey')
    op.create_foreign_key(None, 'user_answers', 'questions', ['question_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'user_answers', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.create_index(op.f('ix_public_users_email'), 'users', ['email'], unique=True, schema='public')
    op.create_index(op.f('ix_public_users_id'), 'users', ['id'], unique=False, schema='public')
    op.drop_index('ix_vocabulary_items_id', table_name='vocabulary_items')
    op.create_index(op.f('ix_public_vocabulary_items_id'), 'vocabulary_items', ['id'], unique=False, schema='public')
    op.drop_constraint('vocabulary_items_lesson_id_fkey', 'vocabulary_items', type_='foreignkey')
    op.create_foreign_key(None, 'vocabulary_items', 'lessons', ['lesson_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vocabulary_items', schema='public', type_='foreignkey')
    op.create_foreign_key('vocabulary_items_lesson_id_fkey', 'vocabulary_items', 'lessons', ['lesson_id'], ['id'])
    op.drop_index(op.f('ix_public_vocabulary_items_id'), table_name='vocabulary_items', schema='public')
    op.create_index('ix_vocabulary_items_id', 'vocabulary_items', ['id'], unique=False)
    op.drop_index(op.f('ix_public_users_id'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_email'), table_name='users', schema='public')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'user_answers', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_answers', schema='public', type_='foreignkey')
    op.create_foreign_key('user_answers_question_id_fkey', 'user_answers', 'questions', ['question_id'], ['id'])
    op.create_foreign_key('user_answers_user_id_fkey', 'user_answers', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_public_user_answers_id'), table_name='user_answers', schema='public')
    op.create_index('ix_user_answers_id', 'user_answers', ['id'], unique=False)
    op.drop_constraint(None, 'questions', schema='public', type_='foreignkey')
    op.drop_index(op.f('ix_public_questions_question_type'), table_name='questions', schema='public')
    op.drop_index(op.f('ix_public_questions_lesson_id'), table_name='questions', schema='public')
    op.drop_index(op.f('ix_public_questions_id'), table_name='questions', schema='public')
    op.create_index('ix_questions_id', 'questions', ['id'], unique=False)
    op.drop_column('questions', 'question_type')
    op.drop_column('questions', 'lesson_id')
    op.drop_index(op.f('ix_public_lessons_topic'), table_name='lessons', schema='public')
    op.drop_index(op.f('ix_public_lessons_title'), table_name='lessons', schema='public')
    op.drop_index(op.f('ix_public_lessons_level'), table_name='lessons', schema='public')
    op.drop_index(op.f('ix_public_lessons_id'), table_name='lessons', schema='public')
    op.create_index('ix_lessons_topic', 'lessons', ['topic'], unique=False)
    op.create_index('ix_lessons_title', 'lessons', ['title'], unique=False)
    op.create_index('ix_lessons_level', 'lessons', ['level'], unique=False)
    op.create_index('ix_lessons_id', 'lessons', ['id'], unique=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.create_table('comprehension_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('correct_option', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name='comprehension_questions_lesson_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comprehension_questions_pkey')
    )
    op.create_index('ix_comprehension_questions_id', 'comprehension_questions', ['id'], unique=False)
    # ### end Alembic commands ###
