"""Add translation column to VocabularyItem

Revision ID: 8a45ddd34763
Revises: 6838bf44552d
Create Date: 2025-04-19 17:02:47.973716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a45ddd34763'
down_revision: Union[str, None] = '6838bf44552d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.drop_constraint('questions_lesson_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'lessons', ['lesson_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('user_answers_question_id_fkey', 'user_answers', type_='foreignkey')
    op.drop_constraint('user_answers_user_id_fkey', 'user_answers', type_='foreignkey')
    op.create_foreign_key(None, 'user_answers', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'user_answers', 'questions', ['question_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('vocabulary_items', sa.Column('translation', sa.String(), nullable=True))
    op.drop_constraint('vocabulary_items_lesson_id_fkey', 'vocabulary_items', type_='foreignkey')
    op.create_foreign_key(None, 'vocabulary_items', 'lessons', ['lesson_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vocabulary_items', schema='public', type_='foreignkey')
    op.create_foreign_key('vocabulary_items_lesson_id_fkey', 'vocabulary_items', 'lessons', ['lesson_id'], ['id'])
    op.drop_column('vocabulary_items', 'translation')
    op.drop_constraint(None, 'user_answers', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'user_answers', schema='public', type_='foreignkey')
    op.create_foreign_key('user_answers_user_id_fkey', 'user_answers', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_answers_question_id_fkey', 'user_answers', 'questions', ['question_id'], ['id'])
    op.drop_constraint(None, 'questions', schema='public', type_='foreignkey')
    op.create_foreign_key('questions_lesson_id_fkey', 'questions', 'lessons', ['lesson_id'], ['id'])
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    # ### end Alembic commands ###
